services:
  - type: web
    name: study-platform
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: study-platform-db
          property: connectionString

databases:
  - name: study-platform-db
    plan: free
